form_questions_for_pretrail = [
                "Petitioner’s Full Name",
                "Address",
                "Phone Number",
                "Petitioner's Date of Birth",
                "Relationship to the Decedent",
                "Decedent's Full Name",
                "Decedent's Date of Birth",
                "Date of Death",
                "What was the residence address of decedent at the time of death?",
                "County",
                "Last 4 Digits of the Social Security Number",
                "What is the driver's license number or state-issued ID number?",
                "Passport Number",
                "Are There Any Other Identifying Details to Provide?",
                "Estimated Value of the Decedent’s Real Estate?",
                "Estimated Value of the Personal Estate (Other Assets)",
                "Time of Death",
                "Was an application previously filed, and was a personal representative appointed informally?",
                "Has a personal representative been previously appointed?",
                "Representative's Full Name",
                "Relationship to the Decedent",
                "Address",
                "The personal representative’s city, state, zip?",
                "Date of Decedent’s Will",
                "Date of Decedent's Will or Codicil",
                "Is/are the will and codicils offered for probate?",
                "Is there any authenticated copy of the will and codicil?",
                "What is the type of fiduciary?",
                "Period of Fiduciary Service",
                "Describe the Real Property or Business Interest",
                "What is the mailing address or address of informant?"
            ]